#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m
kotlin.incremental=false

#Gradle
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

#Kotlin/Native
kotlin.native.ignoreDisabledTargets=true

#Android
android.nonTransitiveRClass=true
