package com.katya.app.ui.settings

import androidx.compose.runtime.Immutable
import com.katya.app.data.EmailAccount
import com.katya.app.data.ImportSection
import com.katya.app.data.Service
import com.katya.app.data.ThemeMode
import com.katya.app.inference.LocalModel
import com.katya.app.mcp.PopularMcpServer

@Immutable
data class SettingsActions(
    val onSelectTab: (SettingsTab) -> Unit,
    val onAddService: (Service) -> Unit,
    val onRemoveService: (String) -> Unit,
    val onReorderServices: (List<String>) -> Unit,
    val onAddEmailAccount: (EmailAccount, String) -> Unit,
    val onExpandService: (String?) -> Unit,
    val onChangeApiKey: (String, String) -> Unit,
    val onChangeBaseUrl: (String, String) -> Unit,
    val onSelectModel: (String, String) -> Unit,
    val onToggleTool: (String, Boolean) -> Unit,
    val onSaveSoul: (String) -> Unit,
    val onChangeSttEngine: (com.katya.app.data.SttEngine) -> Unit,
    val onChangeTtsEngine: (com.katya.app.data.TtsEngine) -> Unit,
    val onToggleDynamicUi: (Boolean) -> Unit,
    val onToggleAgentVisibility: (Boolean) -> Unit,
    val onToggleVoiceResponse: (Boolean) -> Unit,
    val onToggleWakeWord: (Boolean) -> Unit,
    val onChangeWakeWordTrigger: (String) -> Unit,
    val onSelectWakeWordModelLang: (String) -> Unit,
    val onToggleWakeWordVibration: (Boolean) -> Unit,
    val onToggleWakeWordSound: (Boolean) -> Unit,
    val onToggleWatchIntegration: (Boolean) -> Unit,
    val onDownloadVosk: () -> Unit,
    val onAddQuickAction: (com.katya.app.data.QuickAction) -> Unit,
    val onUpdateQuickAction: (com.katya.app.data.QuickAction) -> Unit,
    val onDeleteQuickAction: (String) -> Unit,
    val onChangeThemeMode: (ThemeMode) -> Unit,
    val onToggleMemory: (Boolean) -> Unit,
    val onDeleteMemory: (String) -> Unit,
    val onUpdateMemory: (String, String) -> Unit,
    val onAddMemory: (String, String) -> Unit,
    val onToggleScheduling: (Boolean) -> Unit,
    val onAddScheduledTask: (String, String, Long, String?, com.katya.app.data.TaskTrigger) -> Unit,
    val onUpdateScheduledTask: (com.katya.app.data.ScheduledTask) -> Unit,
    val onCancelTask: (String) -> Unit,
    val onToggleDaemon: (Boolean) -> Unit,
    val onToggleVless: (Boolean) -> Unit,
    val onChangeVlessUri: (String) -> Unit,
    val onShowDeepSeekAuthDialog: (Boolean) -> Unit,
    val onToggleHeartbeat: (Boolean) -> Unit,
    val onChangeHeartbeatInterval: (Int) -> Unit,
    val onChangeHeartbeatActiveHours: (Int, Int) -> Unit,
    val onSaveHeartbeatPrompt: (String) -> Unit,
    val onChangeHeartbeatService: (String?) -> Unit,
    val onRefreshHeartbeat: () -> Unit,
    val onToggleEmail: (Boolean) -> Unit,
    val onRemoveEmailAccount: (String) -> Unit,
    val onChangeEmailPollInterval: (Int) -> Unit,
    val onRefreshEmailAccount: (String) -> Unit,
    val onToggleSms: (Boolean) -> Unit,
    val onChangeSmsPollInterval: (Int) -> Unit,
    val onRefreshSms: () -> Unit,
    val onToggleSmsSend: (Boolean) -> Unit,
    val onToggleNotifications: (Boolean) -> Unit,
    val onOpenNotificationListenerSettings: () -> Unit,
    val onOpenAppPermissionSettings: () -> Unit,
    val onRecheckLocalNetworkPermission: (String) -> Unit,
    val onClearPendingNotifications: () -> Unit,
    val onToggleFreeFallback: (Boolean) -> Unit,
    val onChangeUiScale: (Float) -> Unit,
    val onAddMcpServer: (String, String, Map<String, String>) -> Unit,
    val onRemoveMcpServer: (String) -> Unit,
    val onToggleMcpServer: (String, Boolean) -> Unit,
    val onRefreshMcpServer: (String) -> Unit,
    val onShowAddMcpServerDialog: (Boolean) -> Unit,
    val onAddPopularMcpServer: (PopularMcpServer) -> Unit,
    val onUninstallSkill: (String) -> Unit,
    val onShowAddSkillDialog: (Boolean) -> Unit,
    val onInstallGitHubSkill: (String) -> Unit,
    val onInstallBrowsedSkill: (com.katya.app.skills.RegistrySkillEntry) -> Unit,
    val onDownloadLocalModel: (LocalModel) -> Unit,
    val onCancelLocalModelDownload: () -> Unit,
    val onDeleteLocalModel: (String) -> Unit,
    val onChangeModelContextTokens: (String, Int) -> Unit,
    val onExportSettings: suspend (Set<ImportSection>) -> ByteArray,
    val onPrepareExport: () -> Map<ImportSection, String?>,
    val onImportSettings: (ByteArray, Set<ImportSection>, Boolean) -> ImportResult,
    val onChangeMonitorOverlayMode: (com.katya.app.data.MonitorOverlayMode) -> Unit,
    val onUndoDelete: () -> Unit,
    val onChangeHfRepoUrl: (String) -> Unit,
    val onFetchHfModels: () -> Unit,
) {
    companion object {
        val NoOp = SettingsActions(
            onSelectTab = {},
            onAddService = {},
            onRemoveService = {},
            onReorderServices = {},
            onAddEmailAccount = { _, _ -> },
            onExpandService = {},
            onChangeApiKey = { _, _ -> },
            onChangeBaseUrl = { _, _ -> },
            onSelectModel = { _, _ -> },
            onToggleTool = { _, _ -> },
            onSaveSoul = {},
            onChangeSttEngine = {},
            onChangeTtsEngine = {},
            onToggleDynamicUi = {},
            onToggleAgentVisibility = {},
            onToggleVoiceResponse = {},
            onToggleWakeWord = {},
            onChangeWakeWordTrigger = {},
            onSelectWakeWordModelLang = {},
            onToggleWakeWordVibration = {},
            onToggleWakeWordSound = {},
            onToggleWatchIntegration = {},
            onDownloadVosk = {},
            onAddQuickAction = {},
            onUpdateQuickAction = {},
            onDeleteQuickAction = {},
            onChangeThemeMode = {},
            onToggleMemory = {},
            onDeleteMemory = {},
            onUpdateMemory = { _, _ -> },
            onAddMemory = { _, _ -> },
            onToggleScheduling = {},
            onAddScheduledTask = { _, _, _, _, _ -> },
            onUpdateScheduledTask = {},
            onCancelTask = {},
            onToggleDaemon = {},
            onToggleVless = {},
            onChangeVlessUri = {},
            onShowDeepSeekAuthDialog = {},
            onToggleHeartbeat = {},
            onChangeHeartbeatInterval = {},
            onChangeHeartbeatActiveHours = { _, _ -> },
            onSaveHeartbeatPrompt = {},
            onChangeHeartbeatService = {},
            onRefreshHeartbeat = {},
            onToggleEmail = {},
            onRemoveEmailAccount = {},
            onChangeEmailPollInterval = {},
            onRefreshEmailAccount = {},
            onToggleSms = {},
            onChangeSmsPollInterval = {},
            onRefreshSms = {},
            onToggleSmsSend = {},
            onToggleNotifications = {},
            onOpenNotificationListenerSettings = {},
            onOpenAppPermissionSettings = {},
            onRecheckLocalNetworkPermission = {},
            onClearPendingNotifications = {},
            onToggleFreeFallback = {},
            onChangeUiScale = {},
            onAddMcpServer = { _, _, _ -> },
            onRemoveMcpServer = {},
            onToggleMcpServer = { _, _ -> },
            onRefreshMcpServer = {},
            onShowAddMcpServerDialog = {},
            onAddPopularMcpServer = {},
            onUninstallSkill = {},
            onShowAddSkillDialog = {},
            onInstallGitHubSkill = {},
            onInstallBrowsedSkill = {},
            onDownloadLocalModel = {},
            onCancelLocalModelDownload = {},
            onDeleteLocalModel = {},
            onChangeModelContextTokens = { _, _ -> },
            onExportSettings = { _ -> ByteArray(0) },
            onPrepareExport = { emptyMap() },
            onImportSettings = { _, _, _ -> ImportResult.Failure },
            onChangeMonitorOverlayMode = {},
            onUndoDelete = {},
            onChangeHfRepoUrl = {},
            onFetchHfModels = {},
        )
    }
}
